### PR TITLE
chore: update Dockerfile to support custom command

### PR DESCRIPTION
**Pull request by ImSingee**
## Summary

Modify Dockerfile so we can use cli from the docker image directly.

e.g. This PR adds support for something like `docker run ghcr.io/logto-io/logto:1.3.1 cli db seed`

## Testing

N/A

## Checklist

- [ ] `.changeset`
- [ ] unit tests
- [ ] integration tests
- [ ] docs

OR

- [ x] This PR is not applicable for the checklist

### CODE REVIEW

**Review by wangsijie — APPROVED** [review]

**Review by wangsijie — CHANGES_REQUESTED** [review]
CI failed, we may need to add the "start" command in some places

**Comment by ImSingee** [comment]
@wangsijie I think the only failed CI is because of the misconfigured GitHub action workflow.

The changesets workflow passed 'token: ${{ secrets.BOT_PAT }}' to actions/checkout. But for security reasons, GitHub won't pass any secrets to workflow triggered by PR.

**Comment by ImSingee** [comment]
I glanced at that workflow code, I think it should not run on PR.

The only meaningful action is 

```
      - name: Create pull request
        if: github.event_name == 'push'
        uses: changesets/action@v1
        with:
          version: node .scripts/version.js
          setupGitUser: false
          commit: 'release: version packages'
          title: 'release: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
```

However, it has a `if: github.event_name == 'push'` condition. So, in fact, this action does nothing to PR.

**Comment by wangsijie** [comment]
You are right, I'll take a look and fix it.

**Comment by wangsijie** [comment]
@ImSingee One last action: can you sign your commit with GPG?

**Comment by ImSingee** [comment]
@wangsijie So interesting… Of course I can. But are you sure your meaning is GPG instead of Sign-Off? After merging the GPG sign will be replaced by GitHub.

**Pull request merged**
