### PR TITLE
feat(connector): kakao connector package created

### PR DESCRIPTION
**Pull request by pemassi**
## Summary
Add Kakao Connector (#1758)

## Testing
Tested on local machine

### CODE REVIEW

**Comment by pemassi** [comment]
@charIeszhao Seems like connector image is expected as `svg` file.

image

Is there plan to accept the other image extends, not only `svg`?

**Comment by charIeszhao** [comment]
Yes, we use SVG as it's scalable and thus has the best user experience on the browser. Is there any difficulty to provide an SVG icon for kakao?

**Comment by pemassi** [comment]
@charIeszhao They only provide PNG from the official site.

https://developers.kakao.com/tool/resource/talk

I got the 3rd party SVG logo.

KakaoTalk_logo

**Comment by charIeszhao** [comment]
cool

**Review by orekihoutaro — COMMENTED** [review]
..

**Comment by charIeszhao** [comment]
> ..

@orekihoutaro If you edit your comment, it would be better to keep your previous comment as well (e.g. with strikethrough). Otherwise it looks like a spam. Or you can also delete it if you think it is not needed any more.

Thanks.

**Comment by gao-sun** [comment]
@pemassi do you still time for this connector? 😄

**Comment by pemassi** [comment]
@gao-sun Yeah, I am waiting for new design for connector as you said :)

**Comment by pemassi** [comment]
Move this PR to #1826

**Pull request closed without merging**
