### PR TITLE
feat(console): add mobile web tab in preview

### PR DESCRIPTION
**Pull request by wangsijie**
## Summary

Add a new tab "Mobile Web" in SIE Preview.

## Testing

Notice the Alipay connector:

截屏2022-06-23 下午3 11 54

截屏2022-06-23 下午3 11 57

### CODE REVIEW

**Review by darcyYe — COMMENTED** [review]
Maybe `Mobile web` can be placed as the second tab

**Comment by wangsijie** [comment]
@darcyYe Let's focus on code implementation, put design questions aside, they can be discussed offline.

**Comment by demonzoo** [comment]
Please do remember to put the top status bar back in mobile web view

**Comment by wangsijie** [comment]
Fixed @demonzoo 

image

**Review by demonzoo — APPROVED** [review]

**Pull request merged**
