### PR TITLE
feat: batch query users

### PR DESCRIPTION
**Pull request by lbennett-stacki**
## Summary
Batch query users using comma separated list of ids

## Testing
Development and staging in my own fork, with QA testing. Will add to test suite here if accepted upstream.

## Checklist

- [ ] `.changeset`
- [ ] unit tests
- [ ] integration tests
- [ ] necessary TSDoc comments

### CODE REVIEW

**Comment by charIeszhao** [comment]
Hi @lbennett-stacki, thanks for the contribution.

However, I'm afraid we do have the batch query feature available, by leveraging the [advanced user search](https://docs.logto.io/docs/recipes/manage-users/advanced-user-search/#match-mode-override) feature.

You can build your request search params with the JavaScript code like this:
```ts
new URLSearchParams([
  ['search.id', 'foo'],
  ['search.id', 'bar'],
  ['mode.id', 'exact'],
]);
```
Then the actual request will carry all the specified search params as follows:
```
/api/users?search.id=foo&search.id=bar&mode.id=exact
```

This way, you can query a list of users with their IDs. Please check the documentation and let us know if you have further questions. Thanks!

**Comment by lbennett-stacki** [comment]
> Hi @lbennett-stacki, thanks for the contribution.
> 
> However, I'm afraid we do have the batch query feature available, by leveraging the [advanced user search](https://docs.logto.io/docs/recipes/manage-users/advanced-user-search/#match-mode-override) feature.
> 
> You can build your request search params with the JavaScript code like this:
> 
> ```ts
> new URLSearchParams([
>   ['search.id', 'foo'],
>   ['search.id', 'bar'],
>   ['mode.id', 'exact'],
> ]);
> ```
> 
> Then the actual request will carry all the specified search params as follows:
> 
> ```
> /api/users?search.id=foo&search.id=bar&mode.id=exact
> ```
> 
> This way, you can query a list of users with their IDs. Please check the documentation and let us know if you have further questions. Thanks!

Small question, can we search into a users `customData`?

**Comment by charIeszhao** [comment]
> > Hi @lbennett-stacki, thanks for the contribution.
> > However, I'm afraid we do have the batch query feature available, by leveraging the [advanced user search](https://docs.logto.io/docs/recipes/manage-users/advanced-user-search/#match-mode-override) feature.
> > You can build your request search params with the JavaScript code like this:
> > ```ts
> > new URLSearchParams([
> >   ['search.id', 'foo'],
> >   ['search.id', 'bar'],
> >   ['mode.id', 'exact'],
> > ]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then the actual request will carry all the specified search params as follows:
> > ```
> > /api/users?search.id=foo&search.id=bar&mode.id=exact
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way, you can query a list of users with their IDs. Please check the documentation and let us know if you have further questions. Thanks!
> 
> Small question, can we search into a users `customData`?

Hi, good question. We currently don't support search into `jsonb` type data. But after a quick discussion last week, the team thought it would be great to have it. So please stay tuned and we'll let you know once we have it

**Comment by charIeszhao** [comment]
Due to the coversation above, I'm closing the PR. Feel free to contact us if you have any further questions.

**Pull request closed without merging**
