### PR TITLE
fix(connector): fix wrong image links for apple connector README

### PR DESCRIPTION
**Pull request by xiaohanyu**
## Summary

Simple fix as described in title.

## Testing

Before fix:

image

After fix:

image

## Checklist

- ~~[ ] `.changeset`~~
- ~~[ ] unit tests~~
- ~~[ ] integration tests~~
- ~~[ ] necessary TSDoc comments~~

### CODE REVIEW

**Review by darcyYe — APPROVED** [review]
Thanks for the correction!

**Comment by darcyYe** [comment]
Hold on a second, this change did not resolve the issue that the image resources can not be properly displayed in the console. Will check it later.

**Comment by xiaohanyu** [comment]
@darcyYe I am using relative path here:

```markdown
![Enable Sign in with Apple](./docs/enable-sign-in-with-apple-in-xcode.png)
```

I guess maybe you could use absoluate path, something like:

```markdown
![Enable Sign in with Apple](./packages/connectors/connector-apple/docs/enable-sign-in-with-apple-in-xcode.png)
```

I am not sure how you guys set up the doc site from github which matters to how image path are resolved.

Just FYI.

**Comment by darcyYe** [comment]
> @darcyYe
> 
> Check the source file in my [branch](https://github.com/xiaohanyu/logto/tree/patch-1/packages/connectors/connector-apple) and you can see that the fix works.
> 
> Screenshot:
> 
> image
> I am not sure why github PR preview is not working for no reason.
> 
> image
> For the console thing, not sure how console resolve the img path though, maybe absolute path would work.
> 
> ~I am using relative path here:~
> 
> ```
> Enable Sign in with Apple
> ```
> 
> ~I guess maybe you could use absoluate path, something like:~
> 
> ```
> Enable Sign in with Apple
> ```
> 
> ~I am not sure how you guys set up the doc site from github which matters to how image path are resolved.~
> 
> ~Just FYI.~

No worries, I think the relative path follows the GitHub flavored markdown spec. The issue is that we did not properly parse the path in our console component. Try to fix that and see if the relative path can work on the console.

**Comment by darcyYe** [comment]
The path has been updated in https://github.com/logto-io/logto/pull/5069/files, with not only Apple connector, but also other connectors. Double checked that the image resources can be properly loaded on GitHub page and Logto admin console. This PR can be closed, but many thanks to @xiaohanyu for finding this issue.

**Pull request closed without merging**
