### PR TITLE
feature: add helm charts for logto.

### PR DESCRIPTION
**Pull request by lingdie**
Add helm charts to deploy logto on kubernetes.

Roadmap for logto helm charts

Task | Completed
-- | --
Init helm charts | ✅
Use Bitnami/postgresql as subcharts | no need seems?
Encrypt database url to secret | ☐
Test and bug fix | ☐
Release | ☐

### CODE REVIEW

**Comment by lingdie** [comment]
Hello @gao-sun, I apologize for this PR being late and quite imperfect. You can consider it as a proposal: to create Helm charts for Logto to facilitate its deployment on Kubernetes. If you think this proposal is worth pursuing, I will need your help very much. I am also more than happy to contribute to the Logto community.

**Comment by gao-sun** [comment]
@lingdie thank you. i'm not familiar with the helm charts @wangsijie can you take a look and follow this? thanks

**Comment by lingdie** [comment]
> @lingdie thank you. i'm not familiar with the helm charts @wangsijie can you take a look and follow this? thanks

I will continue to iterate on this PR, but I am not familiar with logto, such as connectors, databases, environment variables, etc., all of which need to be handled in Helm charts.

**Comment by wangsijie** [comment]
Hi, @lingdie let me know if this is ready for test, or need any assistant.

**Comment by lingdie** [comment]
> Hi, @lingdie let me know if this is ready for test, or need any assistant.

Thanks a lot.

**Comment by lingdie** [comment]
@wangsijie I have now initialized the Helm charts for logto, below are the testing-related steps. The main document I referred to when building the Helm charts is 
https://docs.logto.io/docs/references/core/configuration.

```markdown
# Test logto helm charts

Here are some steps to test logto helm charts.

## Install postgresql
```shell
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install logto-postgresql bitnami/postgresql
```

use the following command to get the postgresql url
```shell
#!/bin/bash
password=$(kubectl get secret logto-postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)
export db_url="postgresql://postgres:$password@logto-postgresql.default.svc.cluster.local:5432/postgres"
echo "$db_url"
```

## Helm install logto (before release)

```bash
git clone https://github.com/lingdie/logto.git
cd logto && git checkout helm

# set env.db_url and other envs in values.yaml
# set core.endpoint and admin.endpoint in values.yaml if necessary
helm install logto helm --set common.env.db_url=${db_url}
```

access the logto service by port-forwarding

```bash
kubectl port-forward svc/logto-admin 3002:3002
```
```

During my testing process, the pod crashes and the logs are as follows:
```text
Defaulted container "logto" out of: logto, init (init)

> start
> cd packages/core && NODE_ENV=production node .

(node:17) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
warn [CACHE] No Redis client initialized, skipping
error Error while initializing app:
error error: relation "systems" does not exist
    at Parser.parseErrorMessage (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 106,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '21',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable',
  notices: []
}
error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.

 See https://docs.logto.io/docs/tutorials/using-cli/database-alteration for reference.

npm notice
npm notice New minor version of npm available! 9.5.1 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice
```
It looks like I need to initialize the database. I may need your help with this part.

**Comment by lingdie** [comment]
And during my testing process, the pod crashes and the logs are as follows:
```text
Defaulted container "logto" out of: logto, init (init)

> start
> cd packages/core && NODE_ENV=production node .

(node:17) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
warn [CACHE] No Redis client initialized, skipping
error Error while initializing app:
error error: relation "systems" does not exist
    at Parser.parseErrorMessage (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 106,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '21',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable',
  notices: []
}
error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.

 See https://docs.logto.io/docs/tutorials/using-cli/database-alteration for reference.

npm notice
npm notice New minor version of npm available! 9.5.1 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice
```

It looks like I need to initialize the database. I may need your help with this part.

**Comment by lingdie** [comment]
I have resolved the issue mentioned in the previous comment. Now, this Helm chart can successfully deploy ClusterIP services and their related pods. Regarding ingress and load balance, as well as testing horizontal pod autoscaling (HPA), I will provide guidance and assistance in next step.

**Comment by wangsijie** [comment]
@lingdie is there any update? If you need any help, feel free to hit me.

**Comment by simeng-li** [comment]
Close this PR for now, as it has been put on hold without further activity for a while.

**Pull request closed without merging**
