### PR TITLE
feat(core): copy markdown files to build folder when building project

### PR DESCRIPTION
**Pull request by demonzoo**
## Summary

Copy all markdown files (.md) to `/build` folder when building project

## Linear Issue Reference

[LOG-1935](https://linear.app/silverhand/issue/LOG-1935/copy-readmemd-when-building-project)

## Testing

- [x] Execute `pnpm dev` or `pnpm build`, markdown files in all connectors sub-folders can be found in build destination folder.

image

### CODE REVIEW

**Review by xiaoyijun — APPROVED** [review]
LGTM

**Comment by xiaoyijun** [comment]
Wondering how to deal with it if we have more than 1 copy command?
Can we put the command into a separate file? It may be more convenient if we add more copy commands.

**Review by darcyYe — APPROVED** [review]

**Comment by wangsijie** [comment]
Actully this need to be removed after refacting connectors to a seperate repo.

**Comment by demonzoo** [comment]
> Actully this need to be removed after refacting connectors to a seperate repo.

We still need this in the "Get Started" guide, with an API to fetch all the markdown files for each step.
As for the connector, we can re-use this solution in the new package, right? We still need to copy markdown files to the build folder

**Pull request merged**
