### PR TITLE
chore(*) add connectors wechat miniprogram

### PR DESCRIPTION
**Pull request by zuohuadong**
## Checklist

- [ ] `.changeset`
- [ ] unit tests
- [ ] integration tests
- [ ] docs

OR

- [ ] This PR is not applicable for the checklist

https://github.com/logto-io/logto/issues/3013

In miniprogram simulation, the OAuth2 server passes code to the logto callback address.

### CODE REVIEW

**Comment by wangsijie** [comment]
hi, @zuohuadong thanks for your contribution, but I have a question here:

In order to sign in with WeChat in miniprogram, the user should call `wx.login` to get authentication code, but in Logto's other social connector, we use a "redirect" to get code. So I wonder how are you prepare to call `wx.login`? Do we need to change the Logto's sign in framework?

**Comment by zuohuadong** [comment]
@wangsijie 
Enum has added a new type, now instead of "unti", "native", "web", three. Add another "code" or something else.

**Comment by wangsijie** [comment]
@zuohuadong The code looks good overall.
However, unless I'm mistaken, it seems that the current sign-in process (which calls the Main Flow) may not be able to accommodate signing in via wx.login(). Could you please clarify your plans for the front-end to address this?

**Comment by zuohuadong** [comment]
@wangsijie Auth URL is a callback to logto, the frontend refuses automatic redirection, and the jscode call callback with 'wx.login' appended to the address can be obtained.

**Comment by wangsijie** [comment]
I am still curious about your front-end implementation, can you explain more details or join our [discord channel](https://discord.gg/UEPaF3j5e6) to discuss.

**Pull request closed without merging**
