### PR TITLE
docs: correct react sdk turorial content

### PR DESCRIPTION
**Pull request by 3lang3**
## Summary
correct react sdk turorial content

### CODE REVIEW

**Comment by 3lang3** [comment]
btw logto is awesome

**Review by gao-sun — APPROVED** [review]
great great! thank you

**Comment by 3lang3** [comment]
> great great! thank you

我正在使用logto，demo已经跑好了，准备试着迁过来 ，用着太爽了

**Comment by gao-sun** [comment]
@3lang3 nit: you need to [sign your commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) - after the setup, you can do it via git or using the GitHub web editor

btw, I'm curious what scenario are you trying to use Logto for? A personal project, or in your company.

**Comment by gao-sun** [comment]
@3lang3 I tried to sign the commit for you but I cannot push to your repo ;-)

**Comment by 3lang3** [comment]
> @3lang3 I tried to sign the commit for you but I cannot push to your repo ;-)

sorry,  gpg make me confused, Is that all right now?

**Comment by 3lang3** [comment]
> @3lang3 nit: you need to [sign your commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) - after the setup, you can do it via git or using the GitHub web editor
> 
> btw, I'm curious what scenario are you trying to use Logto for? A personal project, or in your company.

创业团队在写，sass方向，我们想让每个模块专注自己的事，`logto` 的解决方案非常适合我们

**Comment by demonzoo** [comment]
Well, this seems like a regression issue to me. The `clientId` needs to be replaced with `appId` globally for all platforms.

**Comment by gao-sun** [comment]
@3lang3 the second commit is alright, but we require all commits to be signed. you can use `git reset HEAD~2` and commit again - or we can do that for you if you don't mind

**Comment by 3lang3** [comment]
> @3lang3 the second commit is alright, but we require all commits to be signed. you can use `git reset HEAD~2` and commit again - or we can do that for you if you don't mind

plz

**Comment by 3lang3** [comment]
> > > @3lang3 the second commit is alright, but we require all commits to be signed. you can use `git reset HEAD~2` and commit again - or we can do that for you if you don't mind
> > 
> > 
> > i want close this pr, it include noises becuse i wrong git opration
> 
> Well, you don't have to close it. Let me know if it's OK to allow me to update your PR directly

Yes plz update directly

**Pull request merged**
