### PR TITLE
feat(core): `GET /applications`

### PR DESCRIPTION
**Pull request by gao-sun**
## Testing
- [x] `GET /applications` returns all applications in array

### CODE REVIEW

**Comment by wangsijie** [comment]
how about just return an array in body, and put pagination in response header's link? 

https://stackoverflow.com/questions/9742380/link-headers-vs-link-elements-for-restful-json

although, link header is not prefect, we can discuss.

**Comment by gao-sun** [comment]
@wangsijie sounds interesting. let me take a look

**Comment by wangsijie** [comment]
@gao-sun yeah，is cool to keep response body clean.

**Comment by gao-sun** [comment]
@wangsijie i updated to return array and added [LOG-82](https://linear.app/silverhand/issue/LOG-82/design-pagination-metadata) for you ;-) please take a look at this one again

**Review by wangsijie — APPROVED** [review]

**Pull request merged**
