### PR TITLE
chore: add Render deploy

### PR DESCRIPTION
**Pull request by Olyno**
## Summary

This pull request introduces "One Click deploy" section. People can deploy a new instance of Logto in a click.

Currently support:
 - Render

## Testing

/

### CODE REVIEW

**Comment by gao-sun** [comment]
i'm still trying to figure out the best layout, but i'm going to bed today - will try tmw

**Comment by gao-sun** [comment]
@Olyno failed to find a way to make a good layout in gfm, would you mind adding a badge like this instead?

image

**Comment by Olyno** [comment]
I can change the badge design, but suppose we want to add more "One click deploy" buttons in the future (like with Digital Ocean for example), wouldn't it be better to create a separate section?

**Comment by gao-sun** [comment]
@Olyno yes, we can update it to a dedicated section once we have another one-click deploy method. just lmk before you are going to add another one. I can help you to change the design - already in my VSCode lol

**Comment by gao-sun** [comment]
@Olyno btw we require [signed commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) in master branch, lmk if you have any questions during the setup

**Comment by gao-sun** [comment]
the major issue i encountered is the badge design style between GitPod and Render are so different, and they cannot be vertical aligned lol. i would like to ask our designer to make a better one for the "One-click deploy" section.

i'll merge this one first. it's a cool update.

**Review by gao-sun — APPROVED** [review]

**Comment by Olyno** [comment]
> @Olyno btw we require [signed commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) in master branch, lmk if you have any questions during the setup

Ah, i didn't know it was required, my bad. My next commits should be signed automatically! Thank you!

**Pull request merged**
