### PR TITLE
feat(connectors): handle authorization callback parameters in each connector respectively

### PR DESCRIPTION
**Pull request by darcyYe**
## Summary

1. Handle authorization callback parameters in each connector respectively.
2. Add `ConnectorErrorCodes.UnsuccessfulAuthorization` and corresponding error handler.

## Linear Issue Reference

LOG-2929

## Testing

UTs.

### CODE REVIEW

**Review by wangsijie — COMMENTED** [review]
Seems that all `authorizationCallbackHandler` are the same, can we refactor it somehow

**Comment by darcyYe** [comment]
> Seems that all `authorizationCallbackHandler` are the same, can we refactor it somehow

Certain error messages could be thrown for those social connectors that users can cancel the authorization process (in the current stage, Google, FB, Apple, and Github). To throw specific error codes, this method is implemented in each connector respectively. But for the rest social connectors, it is a good idea to wrap it up.

**Review by wangsijie — APPROVED** [review]
nit: `Unsuccessful` or `Failed`?

**Review by IceHe — APPROVED** [review]
Overall LGTM

**Pull request merged**
